// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLILAps6SROcEpHnBdEyUPd_zN19nw59I',
    appId: '1:617384981328:web:28b302b2f86881c432f255',
    messagingSenderId: '617384981328',
    projectId: 'csen268-f24-g2',
    authDomain: 'csen268-f24-g2.firebaseapp.com',
    storageBucket: 'csen268-f24-g2.firebasestorage.app',
    measurementId: 'G-QQ5TV5K4B6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxkURZ0m_-iBHqN3E9izStH2M5Y18kj2M',
    appId: '1:617384981328:android:1a2593cdcf7315e332f255',
    messagingSenderId: '617384981328',
    projectId: 'csen268-f24-g2',
    storageBucket: 'csen268-f24-g2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq1e0SLG826H0nKjVD71Bn9e-YagqUtFU',
    appId: '1:617384981328:ios:ffa68a8c50dc0b3032f255',
    messagingSenderId: '617384981328',
    projectId: 'csen268-f24-g2',
    storageBucket: 'csen268-f24-g2.firebasestorage.app',
    iosClientId: '617384981328-428t171g5tuufqprosoiaeo5p5l2sfvn.apps.googleusercontent.com',
    iosBundleId: 'com.csen268.f24.g2',
  );
}
